services:
  - type: web
    name: fashion-ecommerce-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://Raushan:e8voper3Ogphuq4d@cluster0.pung0de.mongodb.net/fashion_ecommerce?retryWrites=true&w=majority
      - key: CORS_ORIGIN
        value: https://fashion-ecommerce-psi-red.vercel.app,http://localhost:5173
      - key: JWT_SECRET
        value: fashion_secret_key_2026
